//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/InputActions/GameInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputs"",
    ""maps"": [
        {
            ""name"": ""Player L"",
            ""id"": ""0b82a5f3-4a5f-4cd4-9fe3-0a0ed434bd54"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d5d5a249-2c42-48ae-b5e6-e1f3fd0f0369"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AugmentMag"",
                    ""type"": ""Button"",
                    ""id"": ""ea40c82a-6b0b-4055-ad79-a11d8a358fc3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""17533a46-c313-4547-b168-eacf1a6e8f7b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""016ab852-0ca5-45f4-be47-6a1f9c862e33"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AugmentMag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player R"",
            ""id"": ""93613ae5-2239-4675-92ee-d83fcc9dd02a"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6065b8c3-6b4a-46e7-ad88-1fd4e923d417"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AugmentMag"",
                    ""type"": ""Button"",
                    ""id"": ""e7d63bbe-733b-4b13-9e97-526282a14323"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""954df4d5-6941-43af-888e-750f231d3418"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""901278ad-747a-484e-8020-3f8df6d8a7d1"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AugmentMag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Other Key"",
            ""id"": ""d753af44-db13-4c53-b3ec-e2a23f970391"",
            ""actions"": [
                {
                    ""name"": ""SwitchCircle"",
                    ""type"": ""Button"",
                    ""id"": ""c6474103-da59-4b32-9472-b3943c9fced5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""db40c733-7dba-4c9f-8cae-2517918d7abc"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Pose"",
            ""id"": ""5e33eae9-4adb-4cc3-b220-8b0d7c3d0aab"",
            ""actions"": [
                {
                    ""name"": ""SwitchPose"",
                    ""type"": ""Button"",
                    ""id"": ""652c5116-1111-481b-8bc8-611c720601bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectUp"",
                    ""type"": ""Button"",
                    ""id"": ""5f792602-fbe5-4a6a-a6b9-aa711c9825d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectDown"",
                    ""type"": ""Button"",
                    ""id"": ""4cb457f6-b7c5-49b1-b497-a75964ef5ca2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Decide"",
                    ""type"": ""Button"",
                    ""id"": ""4d6641e3-f059-4427-bea0-e6f6d5b6cf39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1177327d-9a77-4a38-8471-29354ba539c1"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchPose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5909d78-8e5c-4563-a866-5b786b474961"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d89a3cc8-53d0-4386-a8de-1dd1430e8b79"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Decide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2da86acb-183e-467c-bc0a-cd343eaa4794"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""QTE"",
            ""id"": ""a425e505-d1b3-4b1a-ae74-c73bf2df49b8"",
            ""actions"": [
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""9859d3aa-ffce-459b-8629-b246c33f7b89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""272eae19-42fc-4d8f-b977-9fbd19d3fe7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""a192200d-b722-4084-8f4f-0d28b9f31305"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""8e263305-820b-44ab-ac35-2a77cc57fdee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4ed34a87-0461-4bcf-b37f-bc2bb9f2eca4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71e390ae-1cfb-4772-ae1d-7d8a75018c32"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d034266-0777-40c2-8211-2ffb4fd6d36e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0353856-be68-44d1-8ebc-c5ea62bd5c88"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Title"",
            ""id"": ""ebb2dbe1-a635-41e2-b980-59f767d99236"",
            ""actions"": [
                {
                    ""name"": ""Decide"",
                    ""type"": ""Button"",
                    ""id"": ""3ee9641c-db3d-4ed2-b1f0-d049807e4f58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d612fe61-2370-4d72-89a5-42fb074f3ce7"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Decide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player L
        m_PlayerL = asset.FindActionMap("Player L", throwIfNotFound: true);
        m_PlayerL_Move = m_PlayerL.FindAction("Move", throwIfNotFound: true);
        m_PlayerL_AugmentMag = m_PlayerL.FindAction("AugmentMag", throwIfNotFound: true);
        // Player R
        m_PlayerR = asset.FindActionMap("Player R", throwIfNotFound: true);
        m_PlayerR_Move = m_PlayerR.FindAction("Move", throwIfNotFound: true);
        m_PlayerR_AugmentMag = m_PlayerR.FindAction("AugmentMag", throwIfNotFound: true);
        // Other Key
        m_OtherKey = asset.FindActionMap("Other Key", throwIfNotFound: true);
        m_OtherKey_SwitchCircle = m_OtherKey.FindAction("SwitchCircle", throwIfNotFound: true);
        // Pose
        m_Pose = asset.FindActionMap("Pose", throwIfNotFound: true);
        m_Pose_SwitchPose = m_Pose.FindAction("SwitchPose", throwIfNotFound: true);
        m_Pose_SelectUp = m_Pose.FindAction("SelectUp", throwIfNotFound: true);
        m_Pose_SelectDown = m_Pose.FindAction("SelectDown", throwIfNotFound: true);
        m_Pose_Decide = m_Pose.FindAction("Decide", throwIfNotFound: true);
        // QTE
        m_QTE = asset.FindActionMap("QTE", throwIfNotFound: true);
        m_QTE_A = m_QTE.FindAction("A", throwIfNotFound: true);
        m_QTE_B = m_QTE.FindAction("B", throwIfNotFound: true);
        m_QTE_X = m_QTE.FindAction("X", throwIfNotFound: true);
        m_QTE_Y = m_QTE.FindAction("Y", throwIfNotFound: true);
        // Title
        m_Title = asset.FindActionMap("Title", throwIfNotFound: true);
        m_Title_Decide = m_Title.FindAction("Decide", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player L
    private readonly InputActionMap m_PlayerL;
    private List<IPlayerLActions> m_PlayerLActionsCallbackInterfaces = new List<IPlayerLActions>();
    private readonly InputAction m_PlayerL_Move;
    private readonly InputAction m_PlayerL_AugmentMag;
    public struct PlayerLActions
    {
        private @GameInputs m_Wrapper;
        public PlayerLActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerL_Move;
        public InputAction @AugmentMag => m_Wrapper.m_PlayerL_AugmentMag;
        public InputActionMap Get() { return m_Wrapper.m_PlayerL; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerLActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerLActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerLActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerLActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @AugmentMag.started += instance.OnAugmentMag;
            @AugmentMag.performed += instance.OnAugmentMag;
            @AugmentMag.canceled += instance.OnAugmentMag;
        }

        private void UnregisterCallbacks(IPlayerLActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @AugmentMag.started -= instance.OnAugmentMag;
            @AugmentMag.performed -= instance.OnAugmentMag;
            @AugmentMag.canceled -= instance.OnAugmentMag;
        }

        public void RemoveCallbacks(IPlayerLActions instance)
        {
            if (m_Wrapper.m_PlayerLActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerLActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerLActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerLActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerLActions @PlayerL => new PlayerLActions(this);

    // Player R
    private readonly InputActionMap m_PlayerR;
    private List<IPlayerRActions> m_PlayerRActionsCallbackInterfaces = new List<IPlayerRActions>();
    private readonly InputAction m_PlayerR_Move;
    private readonly InputAction m_PlayerR_AugmentMag;
    public struct PlayerRActions
    {
        private @GameInputs m_Wrapper;
        public PlayerRActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerR_Move;
        public InputAction @AugmentMag => m_Wrapper.m_PlayerR_AugmentMag;
        public InputActionMap Get() { return m_Wrapper.m_PlayerR; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerRActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerRActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerRActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerRActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @AugmentMag.started += instance.OnAugmentMag;
            @AugmentMag.performed += instance.OnAugmentMag;
            @AugmentMag.canceled += instance.OnAugmentMag;
        }

        private void UnregisterCallbacks(IPlayerRActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @AugmentMag.started -= instance.OnAugmentMag;
            @AugmentMag.performed -= instance.OnAugmentMag;
            @AugmentMag.canceled -= instance.OnAugmentMag;
        }

        public void RemoveCallbacks(IPlayerRActions instance)
        {
            if (m_Wrapper.m_PlayerRActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerRActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerRActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerRActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerRActions @PlayerR => new PlayerRActions(this);

    // Other Key
    private readonly InputActionMap m_OtherKey;
    private List<IOtherKeyActions> m_OtherKeyActionsCallbackInterfaces = new List<IOtherKeyActions>();
    private readonly InputAction m_OtherKey_SwitchCircle;
    public struct OtherKeyActions
    {
        private @GameInputs m_Wrapper;
        public OtherKeyActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchCircle => m_Wrapper.m_OtherKey_SwitchCircle;
        public InputActionMap Get() { return m_Wrapper.m_OtherKey; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OtherKeyActions set) { return set.Get(); }
        public void AddCallbacks(IOtherKeyActions instance)
        {
            if (instance == null || m_Wrapper.m_OtherKeyActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OtherKeyActionsCallbackInterfaces.Add(instance);
            @SwitchCircle.started += instance.OnSwitchCircle;
            @SwitchCircle.performed += instance.OnSwitchCircle;
            @SwitchCircle.canceled += instance.OnSwitchCircle;
        }

        private void UnregisterCallbacks(IOtherKeyActions instance)
        {
            @SwitchCircle.started -= instance.OnSwitchCircle;
            @SwitchCircle.performed -= instance.OnSwitchCircle;
            @SwitchCircle.canceled -= instance.OnSwitchCircle;
        }

        public void RemoveCallbacks(IOtherKeyActions instance)
        {
            if (m_Wrapper.m_OtherKeyActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOtherKeyActions instance)
        {
            foreach (var item in m_Wrapper.m_OtherKeyActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OtherKeyActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OtherKeyActions @OtherKey => new OtherKeyActions(this);

    // Pose
    private readonly InputActionMap m_Pose;
    private List<IPoseActions> m_PoseActionsCallbackInterfaces = new List<IPoseActions>();
    private readonly InputAction m_Pose_SwitchPose;
    private readonly InputAction m_Pose_SelectUp;
    private readonly InputAction m_Pose_SelectDown;
    private readonly InputAction m_Pose_Decide;
    public struct PoseActions
    {
        private @GameInputs m_Wrapper;
        public PoseActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchPose => m_Wrapper.m_Pose_SwitchPose;
        public InputAction @SelectUp => m_Wrapper.m_Pose_SelectUp;
        public InputAction @SelectDown => m_Wrapper.m_Pose_SelectDown;
        public InputAction @Decide => m_Wrapper.m_Pose_Decide;
        public InputActionMap Get() { return m_Wrapper.m_Pose; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PoseActions set) { return set.Get(); }
        public void AddCallbacks(IPoseActions instance)
        {
            if (instance == null || m_Wrapper.m_PoseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PoseActionsCallbackInterfaces.Add(instance);
            @SwitchPose.started += instance.OnSwitchPose;
            @SwitchPose.performed += instance.OnSwitchPose;
            @SwitchPose.canceled += instance.OnSwitchPose;
            @SelectUp.started += instance.OnSelectUp;
            @SelectUp.performed += instance.OnSelectUp;
            @SelectUp.canceled += instance.OnSelectUp;
            @SelectDown.started += instance.OnSelectDown;
            @SelectDown.performed += instance.OnSelectDown;
            @SelectDown.canceled += instance.OnSelectDown;
            @Decide.started += instance.OnDecide;
            @Decide.performed += instance.OnDecide;
            @Decide.canceled += instance.OnDecide;
        }

        private void UnregisterCallbacks(IPoseActions instance)
        {
            @SwitchPose.started -= instance.OnSwitchPose;
            @SwitchPose.performed -= instance.OnSwitchPose;
            @SwitchPose.canceled -= instance.OnSwitchPose;
            @SelectUp.started -= instance.OnSelectUp;
            @SelectUp.performed -= instance.OnSelectUp;
            @SelectUp.canceled -= instance.OnSelectUp;
            @SelectDown.started -= instance.OnSelectDown;
            @SelectDown.performed -= instance.OnSelectDown;
            @SelectDown.canceled -= instance.OnSelectDown;
            @Decide.started -= instance.OnDecide;
            @Decide.performed -= instance.OnDecide;
            @Decide.canceled -= instance.OnDecide;
        }

        public void RemoveCallbacks(IPoseActions instance)
        {
            if (m_Wrapper.m_PoseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPoseActions instance)
        {
            foreach (var item in m_Wrapper.m_PoseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PoseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PoseActions @Pose => new PoseActions(this);

    // QTE
    private readonly InputActionMap m_QTE;
    private List<IQTEActions> m_QTEActionsCallbackInterfaces = new List<IQTEActions>();
    private readonly InputAction m_QTE_A;
    private readonly InputAction m_QTE_B;
    private readonly InputAction m_QTE_X;
    private readonly InputAction m_QTE_Y;
    public struct QTEActions
    {
        private @GameInputs m_Wrapper;
        public QTEActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @A => m_Wrapper.m_QTE_A;
        public InputAction @B => m_Wrapper.m_QTE_B;
        public InputAction @X => m_Wrapper.m_QTE_X;
        public InputAction @Y => m_Wrapper.m_QTE_Y;
        public InputActionMap Get() { return m_Wrapper.m_QTE; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QTEActions set) { return set.Get(); }
        public void AddCallbacks(IQTEActions instance)
        {
            if (instance == null || m_Wrapper.m_QTEActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_QTEActionsCallbackInterfaces.Add(instance);
            @A.started += instance.OnA;
            @A.performed += instance.OnA;
            @A.canceled += instance.OnA;
            @B.started += instance.OnB;
            @B.performed += instance.OnB;
            @B.canceled += instance.OnB;
            @X.started += instance.OnX;
            @X.performed += instance.OnX;
            @X.canceled += instance.OnX;
            @Y.started += instance.OnY;
            @Y.performed += instance.OnY;
            @Y.canceled += instance.OnY;
        }

        private void UnregisterCallbacks(IQTEActions instance)
        {
            @A.started -= instance.OnA;
            @A.performed -= instance.OnA;
            @A.canceled -= instance.OnA;
            @B.started -= instance.OnB;
            @B.performed -= instance.OnB;
            @B.canceled -= instance.OnB;
            @X.started -= instance.OnX;
            @X.performed -= instance.OnX;
            @X.canceled -= instance.OnX;
            @Y.started -= instance.OnY;
            @Y.performed -= instance.OnY;
            @Y.canceled -= instance.OnY;
        }

        public void RemoveCallbacks(IQTEActions instance)
        {
            if (m_Wrapper.m_QTEActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IQTEActions instance)
        {
            foreach (var item in m_Wrapper.m_QTEActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_QTEActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public QTEActions @QTE => new QTEActions(this);

    // Title
    private readonly InputActionMap m_Title;
    private List<ITitleActions> m_TitleActionsCallbackInterfaces = new List<ITitleActions>();
    private readonly InputAction m_Title_Decide;
    public struct TitleActions
    {
        private @GameInputs m_Wrapper;
        public TitleActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Decide => m_Wrapper.m_Title_Decide;
        public InputActionMap Get() { return m_Wrapper.m_Title; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TitleActions set) { return set.Get(); }
        public void AddCallbacks(ITitleActions instance)
        {
            if (instance == null || m_Wrapper.m_TitleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TitleActionsCallbackInterfaces.Add(instance);
            @Decide.started += instance.OnDecide;
            @Decide.performed += instance.OnDecide;
            @Decide.canceled += instance.OnDecide;
        }

        private void UnregisterCallbacks(ITitleActions instance)
        {
            @Decide.started -= instance.OnDecide;
            @Decide.performed -= instance.OnDecide;
            @Decide.canceled -= instance.OnDecide;
        }

        public void RemoveCallbacks(ITitleActions instance)
        {
            if (m_Wrapper.m_TitleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITitleActions instance)
        {
            foreach (var item in m_Wrapper.m_TitleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TitleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TitleActions @Title => new TitleActions(this);
    public interface IPlayerLActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAugmentMag(InputAction.CallbackContext context);
    }
    public interface IPlayerRActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAugmentMag(InputAction.CallbackContext context);
    }
    public interface IOtherKeyActions
    {
        void OnSwitchCircle(InputAction.CallbackContext context);
    }
    public interface IPoseActions
    {
        void OnSwitchPose(InputAction.CallbackContext context);
        void OnSelectUp(InputAction.CallbackContext context);
        void OnSelectDown(InputAction.CallbackContext context);
        void OnDecide(InputAction.CallbackContext context);
    }
    public interface IQTEActions
    {
        void OnA(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
    }
    public interface ITitleActions
    {
        void OnDecide(InputAction.CallbackContext context);
    }
}
